In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier

In [4]:
df = pd.read_csv('../data/2026 QS World University Rankings.csv')

In [6]:
df.head()

  2026 Rank Previous Rank  ... SUS RANK Overall SCORE
0         1             1  ...       33           100
1         2             2  ...       7=          99.4
2         3             6  ...      19=          98.9
3         4             3  ...     198=          97.9
4         5             4  ...     201=          97.7

[5 rows x 30 columns]

In [7]:
df.isnull().sum()

2026 Rank              0
Previous Rank        112
Institution Name       0
Country/Territory      0
Region                 0
Size                   1
Focus                  0
Research               1
Status                47
AR SCORE               0
AR RANK                0
ER SCORE               0
ER RANK                0
FSR SCORE              0
FSR RANK               0
CPF SCORE              0
CPF RANK               0
IFR SCORE             87
IFR RANK              87
ISR SCORE             37
ISR RANK              37
ISD SCORE             37
ISD RANK              37
IRN SCORE              2
IRN RANK               2
EO SCORE               0
EO RANK                0
SUS SCORE             24
SUS RANK              24
Overall SCORE          0
dtype: int64

In [5]:
df.describe()

          AR SCORE     ER SCORE  ...     EO SCORE    SUS SCORE
count  1501.000000  1501.000000  ...  1501.000000  1477.000000
mean     25.785943    26.944237  ...    29.989674    51.254367
std      24.500905    25.504494  ...    29.197573    21.266331
min       1.000000     1.000000  ...     1.000000     3.000000
25%       8.800000     8.500000  ...     6.200000    35.700000
50%      16.000000    16.500000  ...    17.900000    48.700000
75%      32.700000    37.500000  ...    46.000000    66.500000
max     100.000000   100.000000  ...   100.000000   100.000000

[8 rows x 10 columns]