In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier

In [3]:
df = pd.read_csv('../data/2026 QS World University Rankings.csv')

In [4]:
df.head()

,2026 Rank,Previous Rank,Institution Name,Country/Territory,Region,Size,Focus,Research,Status,AR SCORE,...,ISR RANK,ISD SCORE,ISD RANK,IRN SCORE,IRN RANK,EO SCORE,EO RANK,SUS SCORE,SUS RANK,Overall SCORE
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,153,92.3,130,94.1,98,100.0,7,93.8,33,100
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,35,100.0,22,97.5,28,95.9,68,98.3,7=,99.4
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,261,76.1,230,96.5,49,100.0,2,95.4,19=,98.9
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,80,98.7,67,100.0,1,100.0,3,77.9,198=,97.9
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,217,60.6,335,99.4,8,100.0,1,77.8,201=,97.7

In [5]:
df.shape

(1501, 30)

In [6]:
df.isnull().sum()

2026 Rank              0
Previous Rank        112
Institution Name       0
Country/Territory      0
Region                 0
Size                   1
Focus                  0
Research               1
Status                47
AR SCORE               0
AR RANK                0
ER SCORE               0
ER RANK                0
FSR SCORE              0
FSR RANK               0
CPF SCORE              0
CPF RANK               0
IFR SCORE             87
IFR RANK              87
ISR SCORE             37
ISR RANK              37
ISD SCORE             37
ISD RANK              37
IRN SCORE              2
IRN RANK               2
EO SCORE               0
EO RANK                0
SUS SCORE             24
SUS RANK              24
Overall SCORE          0
dtype: int64

In [7]:
df = df.dropna(subset=['Status'])
df.head()

,2026 Rank,Previous Rank,Institution Name,Country/Territory,Region,Size,Focus,Research,Status,AR SCORE,...,ISR RANK,ISD SCORE,ISD RANK,IRN SCORE,IRN RANK,EO SCORE,EO RANK,SUS SCORE,SUS RANK,Overall SCORE
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,153,92.3,130,94.1,98,100.0,7,93.8,33,100
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,35,100.0,22,97.5,28,95.9,68,98.3,7=,99.4
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,261,76.1,230,96.5,49,100.0,2,95.4,19=,98.9
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,80,98.7,67,100.0,1,100.0,3,77.9,198=,97.9
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,217,60.6,335,99.4,8,100.0,1,77.8,201=,97.7

In [8]:
df.isnull().sum()

2026 Rank             0
Previous Rank        94
Institution Name      0
Country/Territory     0
Region                0
Size                  0
Focus                 0
Research              0
Status                0
AR SCORE              0
AR RANK               0
ER SCORE              0
ER RANK               0
FSR SCORE             0
FSR RANK              0
CPF SCORE             0
CPF RANK              0
IFR SCORE            71
IFR RANK             71
ISR SCORE            22
ISR RANK             22
ISD SCORE            22
ISD RANK             22
IRN SCORE             2
IRN RANK              2
EO SCORE              0
EO RANK               0
SUS SCORE            22
SUS RANK             22
Overall SCORE         0
dtype: int64

In [9]:
df.dtypes

2026 Rank             object
Previous Rank         object
Institution Name      object
Country/Territory     object
Region                object
Size                  object
Focus                 object
Research              object
Status                object
AR SCORE             float64
AR RANK               object
ER SCORE             float64
ER RANK               object
FSR SCORE            float64
FSR RANK              object
CPF SCORE            float64
CPF RANK              object
IFR SCORE            float64
IFR RANK              object
ISR SCORE            float64
ISR RANK              object
ISD SCORE            float64
ISD RANK              object
IRN SCORE            float64
IRN RANK              object
EO SCORE             float64
EO RANK               object
SUS SCORE            float64
SUS RANK              object
Overall SCORE         object
dtype: object

In [10]:
df.replace(r'[^\d.]', '', regex=True)

,2026 Rank,Previous Rank,Institution Name,Country/Territory,Region,Size,Focus,Research,Status,AR SCORE,...,ISR RANK,ISD SCORE,ISD RANK,IRN SCORE,IRN RANK,EO SCORE,EO RANK,SUS SCORE,SUS RANK,Overall SCORE
0,1,1,,,,,,,,100.0,...,153,92.3,130,94.1,98,100.0,7,93.8,33,100
1,2,2,,,,,,,,99.6,...,35,100.0,22,97.5,28,95.9,68,98.3,7,99.4
2,3,6,,,,,,,,100.0,...,261,76.1,230,96.5,49,100.0,2,95.4,19,98.9
3,4,3,,,,,,,,100.0,...,80,98.7,67,100.0,1,100.0,3,77.9,198,97.9
4,5,4,,,,,,,,100.0,...,217,60.6,335,99.4,8,100.0,1,77.8,201,97.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1496,1401,12011400,,,,,,,,7.2,...,801,4.8,801,40.9,801,15.5,801,19.5,801,
1497,1401,12011400,,,,,,,,5.7,...,546,40.2,502,12.2,801,3.5,801,20.4,801,
1498,1401,NaN,,,,,,,,8.3,...,801,7.4,801,31.5,801,3.2,801,43.0,801,
1499,1401,12011400,,,,,,,,4.4,...,801,8.9,801,15.4,801,1.7,801,22.5,801,
1500,1401,12011400,,,,,,,,6.5,...,658,24.7,689,2.5,801,1.9,801,11.5,801,

In [11]:
numeric_cols = [
  '2026 Rank', 'Previous Rank',
  'IFR SCORE', 'IFR RANK',
  'ISR SCORE', 'ISR RANK',
  'ISD SCORE', 'ISD RANK',
  'IRN SCORE', 'IRN RANK',
  'SUS SCORE', 'SUS RANK'
]

for col in numeric_cols:
  df[col] = pd.to_numeric(df[col], errors='coerce')

In [12]:
for col in numeric_cols:
  df[col] = df[col].fillna(df[col].median)

In [15]:
df.isnull().sum()

2026 Rank            0
Previous Rank        0
Institution Name     0
Country/Territory    0
Region               0
Size                 0
Focus                0
Research             0
Status               0
AR SCORE             0
AR RANK              0
ER SCORE             0
ER RANK              0
FSR SCORE            0
FSR RANK             0
CPF SCORE            0
CPF RANK             0
IFR SCORE            0
IFR RANK             0
ISR SCORE            0
ISR RANK             0
ISD SCORE            0
ISD RANK             0
IRN SCORE            0
IRN RANK             0
EO SCORE             0
EO RANK              0
SUS SCORE            0
SUS RANK             0
Overall SCORE        0
dtype: int64

In [14]:
df.dtypes

2026 Rank             object
Previous Rank         object
Institution Name      object
Country/Territory     object
Region                object
Size                  object
Focus                 object
Research              object
Status                object
AR SCORE             float64
AR RANK               object
ER SCORE             float64
ER RANK               object
FSR SCORE            float64
FSR RANK              object
CPF SCORE            float64
CPF RANK              object
IFR SCORE             object
IFR RANK              object
ISR SCORE             object
ISR RANK              object
ISD SCORE             object
ISD RANK              object
IRN SCORE             object
IRN RANK              object
EO SCORE             float64
EO RANK               object
SUS SCORE             object
SUS RANK              object
Overall SCORE         object
dtype: object

In [13]:
df.describe()

          AR SCORE     ER SCORE    FSR SCORE    CPF SCORE     EO SCORE
count  1454.000000  1454.000000  1454.000000  1454.000000  1454.000000
mean     26.214168    27.404058    33.989615    30.742710    30.174759
std      24.685689    25.707514    28.381924    29.809824    29.222943
min       1.000000     1.000000     1.000000     1.000000     1.000000
25%       8.900000     8.800000    11.000000     6.000000     6.400000
50%      16.450000    16.900000    23.550000    18.600000    18.200000
75%      33.375000    38.275000    50.450000    50.875000    46.175000
max     100.000000   100.000000   100.000000   100.000000   100.000000